### ISSUE TITLE
[BUG] Doesn't compile with Python 3.11 due to deprecated functions

### ISSUE THREAD

**Issue by 6wl** [NobodyXu/swaystatus#50]
**Describe the bug**
Compiling with Python 3.11 fails

**To Reproduce**
Steps to reproduce the behaviour:
1. Download Fedora 37 beta, this includes Python 3.11 rc1 ish
2. Compile the code
3. Get a few compile errors
4. python3.cc:129:5: error: 'PySys_SetArgvEx' is deprecated
5. python3.cc:145:5: error: 'Py_SetProgramName' is deprecated

**Expected behavior**
Compile before and after the change

**Actual behavior**
Fails to compile with 3.11

**Comment by NobodyXu** [comment]
I don't have much time for this project right now, would you like to open a PR for this?

**Comment by OhseyDev** [comment]
I've already implemented a patch and tested it. I would happily contribute it.

**Comment by NobodyXu** [comment]
Thanks, I'm willing to review and merge it a PR for this, then create a new release.

**Comment by OhseyDev** [comment]
As the patch has been applied, can this issue be closed?

**Comment by NobodyXu** [comment]
Yes, thanks, I forgot to close this issue
